// scenarios.js — the 8 Demo steps AS DATA. Single source of truth for Demo mode
// AND the Overview view (U11), mirroring scripts/demo.sh exactly (persona, scope,
// path, tool, args, expected verdict). Customer-facing copy fields: headline,
// proves, why, railLabel (per scene); identity, verdictLabel (per call). The
// verdictLabel is the honest per-call display label — NEVER the raw classifier
// enum (U8: step-1 call-3 is the REST scope/audience gate, not "acl-deny").
// Shared by server (/api/scenarios) and client.

export const scenarios = [
  {
    id: "oidc", n: 1, title: "REST OIDC gates", tag: "OIDC", railLabel: "Protected APIs",
    headline: "The raw APIs are already protected",
    proves: "Authentication + per-scope authorization at the edge — before MCP exists.",
    setup: "Before any MCP exists, the raw REST APIs are already locked down. We'll hit the dealer API three ways — no token, the right persona, and the wrong scope — and watch Kong's OIDC gate decide each.",
    takeaway: "Authentication and scope/audience are enforced at the edge, before a single tool is generated. Now let's turn those same APIs into MCP tools.",
    why: "Dana's token carries dealers:read but not finance:read, so it has no finance-api audience — the finance route rejects it. That is the REST OIDC scope/audience gate, before any MCP tool exists.",
    narration: "The raw APIs are protected before any MCP. No token → 401; dana (dealers:read) → 200; dana on the finance API → 403 (scope+audience).",
    calls: [
      { label: "no-token → /api/dealers/customers", persona: null, identity: "no-token", verdictLabel: "401 · no token", kind: "rest",
        path: "/api/dealers/customers", method: "GET", expect: { verdict: "auth-fail" } },
      { label: "dana → /api/dealers/customers", persona: "dana", identity: "Dana", verdictLabel: "200 · allowed", kind: "rest",
        path: "/api/dealers/customers", method: "GET", expect: { verdict: "allow" } },
      { label: "dana → /api/finance/invoices (wrong scope+aud)", persona: "dana", identity: "Dana", verdictLabel: "403 · REST scope/audience gate", kind: "rest",
        path: "/api/finance/invoices", method: "GET", expect: { verdict: "acl-deny" },
        note: "403 from the inner OIDC gate (scope+audience), shown as a deny." },
    ],
  },
  {
    id: "convert", n: 2, title: "REST → MCP conversion", tag: "CONVERT", railLabel: "REST → MCP",
    headline: "Kong converts those APIs into MCP tools",
    proves: "REST→MCP conversion with zero rewrite of the upstream services.",
    setup: "Kong converts each governed REST route into an MCP tool and aggregates them by tag. We'll list the tools on three endpoints and see the same APIs show up as callable MCP tools.",
    takeaway: "One REST surface, now discoverable as MCP tools — and the catalog Olivia is shown is already scoped to her groups. Next: what happens when someone calls a tool they aren't entitled to.",
    why: "The catalog is ACL-filtered per identity, so these counts are Olivia's: she sees invoices on /mcp/finance but not floorplans, which is finance-only. A tool she cannot call is simply absent from her list.",
    narration: "Same APIs, now MCP tools, tag-aggregated. As olivia: /mcp/dealers = 2 tools, /mcp/finance = 1 (invoices — floorplans is finance-only and filtered out), /mcp/ops = 2 bundled (dealer+finance).",
    calls: [
      { label: "/mcp/dealers tools/list", persona: "olivia", identity: "Olivia", verdictLabel: "200 · 2 tools", kind: "mcp", path: "/mcp/dealers",
        tool: null, method: "tools/list", expect: { verdict: "allow" } },
      { label: "/mcp/finance tools/list", persona: "olivia", identity: "Olivia", verdictLabel: "200 · 1 tool (floorplans filtered out)", kind: "mcp", path: "/mcp/finance",
        tool: null, method: "tools/list", expect: { verdict: "allow" },
        note: "list_floorplans is allow:[finance] only, so it never appears in an ops catalog — the ACL filters tools/list, not just tools/call." },
      { label: "/mcp/ops tools/list", persona: "olivia", identity: "Olivia", verdictLabel: "200 · 2 bundled", kind: "mcp", path: "/mcp/ops",
        tool: null, method: "tools/list", expect: { verdict: "allow" } },
    ],
  },
  {
    id: "acl", n: 3, title: "Persona tool ACL", tag: "ACL", railLabel: "Per-user tools",
    headline: "Each person only gets the tools their group allows",
    proves: "Per-identity tool authorization straight from a JWT groups claim.",
    setup: "Every persona gets only the tools their group allows, decided straight from the JWT groups claim — no Kong consumers in the path. Watch each persona call their own tools, and Frank get blocked on a dealer tool.",
    takeaway: "Per-identity tool authorization from a token claim, enforced at the gateway before the upstream. Next: how a tool-only token still reaches the APIs.",
    why: "Frank's groups:[finance] is not in that tool's allow-list [dealers, ops] — blocked at the gateway, never reaches the API.",
    narration: "Filtering by the token's groups claim — the access decision uses no Kong consumers (consumers exist only for analytics attribution). Each persona may call ALL their group's tools; frank (finance) may NOT call a dealer tool.",
    calls: [
      { label: "dana → list_dealer_customers @ /mcp/dealers", persona: "dana", identity: "Dana", verdictLabel: "200 · allowed", kind: "mcp",
        path: "/mcp/dealers", tool: "list_dealer_customers", args: {}, expect: { verdict: "allow" } },
      { label: "dana → list_dealer_vehicles @ /mcp/dealers", persona: "dana", identity: "Dana", verdictLabel: "200 · allowed", kind: "mcp",
        path: "/mcp/dealers", tool: "list_dealer_vehicles", args: {}, expect: { verdict: "allow" } },
      { label: "frank → list_invoices @ /mcp/finance", persona: "frank", identity: "Frank", verdictLabel: "200 · allowed", kind: "mcp",
        path: "/mcp/finance", tool: "list_invoices", args: {}, expect: { verdict: "allow" } },
      { label: "frank → list_floorplans @ /mcp/finance", persona: "frank", identity: "Frank", verdictLabel: "200 · allowed", kind: "mcp",
        path: "/mcp/finance", tool: "list_floorplans", args: {}, expect: { verdict: "allow" } },
      { label: "olivia → list_invoices @ /mcp/ops", persona: "olivia", identity: "Olivia", verdictLabel: "200 · allowed", kind: "mcp",
        path: "/mcp/ops", tool: "list_invoices", args: {}, expect: { verdict: "allow" } },
      { label: "frank → list_dealer_customers @ /mcp/ops", persona: "frank", identity: "Frank", verdictLabel: "403 · tool ACL — group not allowed", kind: "mcp",
        path: "/mcp/ops", tool: "list_dealer_customers", args: {}, expect: { verdict: "acl-deny" } },
    ],
  },
  {
    id: "exchange", n: 4, title: "RFC 8693 token exchange", tag: "EXCHANGE", railLabel: "Token exchange",
    showExchange: true,
    headline: "Kong exchanges a narrow token so the call can reach the API",
    proves: "RFC 8693 token exchange — the client never holds API credentials; Kong bridges trust.",
    setup: "An agent token carrying only mcp:use has none of the API audiences the inner gate needs. On /mcp/ops Kong performs an RFC 8693 exchange; on /mcp/dealers it doesn't. Same token, two outcomes.",
    takeaway: "Kong bridges the MCP identity to the API identity exactly where policy allows it — no broad-scope tokens handed to agents. Next: a rule the tool ACL can't express.",
    why: "Same token, two routes. On /mcp/ops Kong swaps the audience to [dealer-api, finance-api] so the inner gate passes; on /mcp/dealers there is no exchange, so the inner gate 403s.",
    narration: "A token with ONLY 'mcp:use' lacks the dealer-api/finance-api audiences the inner gates need. On /mcp/ops Kong exchanges it so the call reaches the API; on /mcp/dealers it can't.",
    calls: [
      { label: "mcp:use-only olivia → /mcp/ops list_dealer_customers", persona: "olivia", identity: "Olivia", verdictLabel: "exchanged → 200",
        scope: "openid mcp:use", kind: "mcp", path: "/mcp/ops", tool: "list_dealer_customers",
        args: {}, expect: { verdict: "allow" }, note: "Kong exchanges the token here." },
      { label: "mcp:use-only olivia → /mcp/dealers list_dealer_customers", persona: "olivia", identity: "Olivia", verdictLabel: "403 · no audience (not exchanged)",
        scope: "openid mcp:use", kind: "mcp", path: "/mcp/dealers", tool: "list_dealer_customers",
        args: {}, expect: { verdict: "inner-gate-deny" }, note: "No exchange here → inner-gate 403." },
    ],
  },
  {
    id: "opa", n: 5, title: "External OPA policy", tag: "OPA", railLabel: "OPA policy",
    headline: "An external policy decides on the request's arguments",
    proves: "Externalized, argument-aware policy (OPA) that hot-reloads without touching Kong.",
    setup: "Some rules live in an argument, not a tool name. We'll call an allowed tool with a benign argument, then with query_status=overdue, and let external OPA make the call.",
    takeaway: "Argument-level policy as code, hot-reloaded with no Kong sync — governance the ACL alone can't reach. Next: governing MCP servers Kong didn't build.",
    why: "Olivia is fully entitled to list_invoices — but the OPA rule denies the overdue filter specifically. Edit mcp.rego and the decision changes live, with no Kong sync.",
    narration: "A rule the tool ACL cannot express: OPA denies list_invoices when the call argument query_status=overdue, even for a permitted caller. opa/policies/mcp.rego hot-reloads with no Kong sync.",
    calls: [
      { label: "olivia → list_invoices (no filter)", persona: "olivia", identity: "Olivia", verdictLabel: "200 · allowed", kind: "mcp",
        path: "/mcp/ops", tool: "list_invoices", args: {}, expect: { verdict: "allow" } },
      { label: "olivia → list_invoices query_status=overdue", persona: "olivia", identity: "Olivia", verdictLabel: "403 · OPA policy", kind: "mcp",
        path: "/mcp/ops", tool: "list_invoices", args: { query_status: "overdue" },
        expect: { verdict: "opa-deny" } },
    ],
  },
  {
    id: "remote", n: 6, title: "Passthrough remotes", tag: "REMOTE", railLabel: "Remote MCP",
    headline: "Kong governs MCP servers it didn't even build",
    proves: "One governed front door for any MCP server, including ones you don't own.",
    setup: "Kong can front MCP servers it never converted — one you own, and a third-party one you don't. We'll hit a passthrough remote unauthenticated, then authenticated.",
    takeaway: "The same OAuth wraps remote MCP servers, including third-party ones — one control plane over all of it. Next: what happens when the server is one we wrote ourselves.",
    why: "The remote MCP servers do their own thing upstream; Kong still requires a valid cox-auto token before anything reaches them.",
    narration: "Govern MCP servers Kong did not convert. /mcp/remote → local market-mcp (Cox tools); /mcp/remote-public → DeepWiki (third-party). Both require a cox-auto token.",
    calls: [
      { label: "/mcp/remote unauth", persona: null, identity: "no-token", verdictLabel: "401 · no token", kind: "mcp", path: "/mcp/remote",
        tool: null, method: "tools/list", expect: { verdict: "auth-fail" } },
      { label: "/mcp/remote-public authed tools/list", persona: "olivia", identity: "Olivia", verdictLabel: "200 · allowed", kind: "mcp",
        path: "/mcp/remote-public", tool: null, method: "tools/list", expect: { verdict: "allow" } },
    ],
  },
  {
    id: "custom", n: 7, title: "Custom tool, governed", tag: "CUSTOM", railLabel: "Custom tool",
    headline: "A tool we wrote by hand — governed exactly like a converted one",
    proves: "Per-group authorization on a tool Kong never generated, written in any language.",
    setup: "This server isn't a converted REST API — it's a Python MCP server we hand-wrote, and Kong doesn't generate its tool. We'll show the catalog differs by person, then call the same tool as three people: dealers and finance are allowed, ops is not.",
    takeaway: "Governance doesn't depend on Kong having authored the tool. A team can ship an MCP server in any language and inherit the same identity-based entitlement — enforced at the gateway, with nothing in the server's own code. Finally, how clients discover all of this.",
    why: "The ACL entry matches the remote tool by NAME on the passthrough listener — it generates nothing. allow: [finance, dealers] omits ops on purpose, so olivia is filtered out of the catalog and denied on the call, the same shape as list_floorplans.",
    narration: "Hand-written Python MCP server at /mcp/custom, fronted by ai-mcp-proxy passthrough-listener with a per-tool ACL (allow: finance, dealers). Kong governs a tool it never generated.",
    calls: [
      { label: "dana → /mcp/custom tools/list", persona: "dana", identity: "Dana", verdictLabel: "200 · 1 tool visible", kind: "mcp",
        path: "/mcp/custom", tool: null, method: "tools/list", expect: { verdict: "allow" } },
      { label: "olivia → /mcp/custom tools/list (ops not entitled)", persona: "olivia", identity: "Olivia", verdictLabel: "200 · empty catalog — filtered by ACL", kind: "mcp",
        path: "/mcp/custom", tool: null, method: "tools/list", expect: { verdict: "allow" },
        note: "The call itself succeeds — it is the CATALOG that is empty. A well-behaved client simply never sees the tool." },
      { label: "dana → hello_custom_tool", persona: "dana", identity: "Dana", verdictLabel: "200 · allowed", kind: "mcp",
        path: "/mcp/custom", tool: "hello_custom_tool", args: {}, expect: { verdict: "allow" },
        note: "Returns \"Hello from custom tool\" — straight from the Python server, through every Kong gate." },
      { label: "frank → hello_custom_tool (different group, also allowed)", persona: "frank", identity: "Frank", verdictLabel: "200 · allowed", kind: "mcp",
        path: "/mcp/custom", tool: "hello_custom_tool", args: {}, expect: { verdict: "allow" },
        note: "Frank is denied dealer tools elsewhere yet allowed here — entitlement is per-tool, not per-person." },
      { label: "olivia → hello_custom_tool (direct call, bypassing the filtered list)", persona: "olivia", identity: "Olivia", verdictLabel: "403 · tool ACL — group not allowed", kind: "mcp",
        path: "/mcp/custom", tool: "hello_custom_tool", args: {}, expect: { verdict: "acl-deny" },
        note: "Call-time enforcement still exists underneath the filtered catalog — naming the tool directly does not get you past it." },
    ],
  },
  {
    id: "registry", n: 8, title: "MCP Registry discovery", tag: "REGISTRY", railLabel: "Registry",
    headline: "Every server is discoverable in the Konnect MCP Registry",
    proves: "Governed discovery — a sanctioned catalog, not ad-hoc URLs.",
    setup: "Every governed server is published to the Konnect MCP Registry so any client can discover it by its canonical URL. We'll list what's discoverable right now.",
    takeaway: "Discovery, governance, and analytics for MCP in one place — the full Cox governed-MCP story, end to end.",
    why: "dealers, finance, ops, remote (market-mcp), remote-public (DeepWiki) and custom (the hand-written Python server) — each advertised at its http://localhost:8000/mcp/* address, discoverable by any host client. The registry lists SERVERS, not tools: a client connects to the URL and calls tools/list to learn what it may use, which is why the catalog it gets back is identity-specific.",
    narration: "The servers are catalogued in Konnect's MCP Registry — discoverable by any host-side client (e.g. Claude Code).",
    calls: [
      { label: "Konnect MCP Registry — discover servers", identity: "Konnect", verdictLabel: "servers listed", kind: "registry",
        expect: { verdict: "allow" } },
    ],
  },
];

export default scenarios;
